/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ControlCadastroProduto;
import Modelo.ModeloCadastrarProduto;
import Modelo.ModeloRealizarVenda;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IMMilengo
 */

public class CadastroProduto extends javax.swing.JFrame {
    ControlCadastroProduto ccp=new ControlCadastroProduto();

    /**
     * Creates new form CadastroProduto
     */
    public CadastroProduto() {
        initComponents();
        ArrayList<String> lista=new ArrayList();
        try {
            BufferedReader ler=new BufferedReader(new FileReader("CadastroProduto.txt"));
            String linha;
            while((linha=ler.readLine())!=null){
            lista.add(linha);
            }
            Collections.sort(lista);
            for(String linhas:lista){
                System.out.println(linhas);
            }
            BufferedWriter escreve=new BufferedWriter(new FileWriter("CadastroProduto.txt"));
            for(String linhas:lista){
            escreve.write(linhas+"\n");
           
            }
            escreve.close();
            
            ler.close();
        } catch (Exception e) {
        }
        
      actualizartabela();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaproduto = new javax.swing.JTable();
        txtpesquisar = new javax.swing.JTextField();
        bpesquisar = new javax.swing.JButton();
        batualizartabela = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Prateleira");

        tabelaproduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do Produto", "Preco do Produto", "Quantidade de Unidades", "ID do Produto", "Data ", "Validade"
            }
        ));
        jScrollPane1.setViewportView(tabelaproduto);

        bpesquisar.setText("Pesquisar");
        bpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpesquisarActionPerformed(evt);
            }
        });

        batualizartabela.setText("Actualizar Tabela");
        batualizartabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batualizartabelaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(286, 286, 286)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(batualizartabela, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batualizartabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

     // String cabecalho[]={"Nome Do Produto","Preco Do Produto","Quantidade de Unidades","ID do Produto","Data "};
    //public void actualizartabela(){
    //ccp.preencherarraylist();
    //tabelaproduto.setModel(new DefaultTableModel(ccp.transformarlistaobjeto(),cabecalho));
    //}
    
    private void batualizartabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batualizartabelaActionPerformed
        // TODO add your handling code here:
         actualizartabela();
    }//GEN-LAST:event_batualizartabelaActionPerformed

    private void bpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpesquisarActionPerformed
        // TODO add your handling code here:
         
      //String dados=txtpesquisar.getText().trim();
       String item=txtpesquisar.getText();
          try(BufferedReader leitor=new BufferedReader(new FileReader("CadastroProduto.txt"))) {
          
          String linha;
          DefaultTableModel dfm=(DefaultTableModel) tabelaproduto.getModel();
          dfm.setRowCount(0);
          while((linha=leitor.readLine())!=null){
          if(linha.contains(item)){
           String[] partir=linha.split(";");
          
          dfm.addRow(partir);
         
          }
          }
          }catch(Exception e){
          
          }
        
      /*if(!(dados.equals(" "))){
      ccp.pesquisar(dados);
      tabelaproduto.setModel(new DefaultTableModel(ccp.transformarlistaobjeto(), cabecalho));
      
      }else{
      JOptionPane.showMessageDialog(this, "Digite o que queres pesquisar");
      }*/
    }//GEN-LAST:event_bpesquisarActionPerformed
private void actualizartabela(){
try(BufferedReader lendo=new BufferedReader(new FileReader("CadastroProduto.txt"))){
    DefaultTableModel dtm=(DefaultTableModel)tabelaproduto.getModel();
    dtm.setRowCount(0);
    String linha;
    while((linha=lendo.readLine())!=null){
        String[] divide=linha.split(";");
        dtm.addRow(divide);
    
    }
    
    lendo.close();
}catch(Exception e){}





}
  
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batualizartabela;
    private javax.swing.JButton bpesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaproduto;
    private javax.swing.JTextField txtpesquisar;
    // End of variables declaration//GEN-END:variables
}
