/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ControlCadastroFuncionario;
import Modelo.ModeloCadastrarFuncionario;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IMMilengo
 */
public class CadastroFuncionario extends javax.swing.JFrame {
String genero;
ControlCadastroFuncionario ccf=new ControlCadastroFuncionario();
    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
        setLocationRelativeTo(this);
         ArrayList<String> lista=new ArrayList();
        try {
            BufferedReader ler=new BufferedReader(new FileReader("CadastroFuncionario.txt"));
            String linha;
            while((linha=ler.readLine())!=null){
            lista.add(linha);
            }
            Collections.sort(lista);
            for(String linhas:lista){
                System.out.println(linhas);
            }
            BufferedWriter escreve=new BufferedWriter(new FileWriter("CadastroFuncionario.txt"));
            for(String linhas:lista){
            escreve.write(linhas+"\n");
           
            }
            escreve.close();
            
            ler.close();
        } catch (Exception e) {
        }
        
        
        
        actualizartabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        javax.swing.ButtonGroup buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabelaf = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCnacionalidade = new javax.swing.JComboBox<>();
        jRmasculino = new javax.swing.JRadioButton();
        jRfeminino = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        balterar = new javax.swing.JButton();
        btsalvar = new javax.swing.JButton();
        beliminar = new javax.swing.JButton();
        jLfoto = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtpesquisar = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        batualizartabela = new javax.swing.JButton();
        Jdata = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtnusuario = new javax.swing.JTextField();
        jprivilegio = new javax.swing.JComboBox<>();
        txtpw = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Cadastrar Funcionário");

        Tabelaf.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabelaf);

        jLabel2.setText("Data de Nascimento :");

        jLabel3.setText("Sexo :");

        jLabel4.setText("Nacionalidade :");

        jLabel5.setText("Nome :");

        jCnacionalidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhuma", "Angolano", "Brasileiro", "Cabo-Verdiano", "Equatoriano", "Guinense", "Moçambicano", "Portugues", "São Tomense", "Timor-Lestino" }));

        buttonGroup1.add(jRmasculino);
        jRmasculino.setText("Masculino");

        buttonGroup1.add(jRfeminino);
        jRfeminino.setText("Feminino");

        jButton1.setText("ADD");

        balterar.setText("Alterar");
        balterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                balterarActionPerformed(evt);
            }
        });

        btsalvar.setText("Salvar");
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        beliminar.setText("Eliminar");
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });

        jLfoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Pesquisa :");

        jButton5.setText("Pesquisar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        batualizartabela.setText("Atualizar Tabela");
        batualizartabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batualizartabelaActionPerformed(evt);
            }
        });

        jLabel6.setText("Nome de usuário:");

        jLabel8.setText("Palavra Passe:");

        jLabel10.setText("Privilégio:");

        jprivilegio.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nenhum", "Administrador", "Funcionário" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(100, 100, 100)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(Jdata, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jCnacionalidade, 0, 212, Short.MAX_VALUE)
                                            .addComponent(txtnome)
                                            .addComponent(txtnusuario)
                                            .addComponent(jprivilegio, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtpw, javax.swing.GroupLayout.Alignment.LEADING))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(balterar)
                                        .addGap(47, 47, 47)
                                        .addComponent(beliminar))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(42, 42, 42)
                                        .addComponent(jRmasculino)
                                        .addGap(28, 28, 28)
                                        .addComponent(jRfeminino)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(btsalvar)
                                        .addGap(292, 292, 292)
                                        .addComponent(batualizartabela))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel6)
                            .addComponent(jLabel8))
                        .addGap(64, 225, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton1)))
                        .addGap(108, 108, 108))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jCnacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jButton1))
                    .addComponent(txtnusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtpw, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jprivilegio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jRfeminino)
                    .addComponent(jRmasculino))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(Jdata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btsalvar)
                    .addComponent(balterar)
                    .addComponent(beliminar)
                    .addComponent(batualizartabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 String cabecalho[]={"Nome","Nacionalidade","Sexo","Nome de usuario","Palavra-Passe","Privilégio","Data de Nascimento"};
    public void actualizartabela(){
    ccf.preencherarraylist();
    Tabelaf.setModel(new DefaultTableModel(ccf.transformarlistaobjeto(),cabecalho));
    }
    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        // TODO add your handling code here:
           try{
            BufferedWriter conexao;
            String nome,nacionalidade,sexo,data,palavrapw,confirmarpw,privilegio,palavrapasseusada,username;
         
        nome=txtnome.getText().toString().trim();
        nacionalidade=jCnacionalidade.getSelectedItem().toString().trim();
        if(jRfeminino.isSelected()){
        genero=jRfeminino.getText().trim();
        
        }else if(jRmasculino.isSelected()){
        genero=jRmasculino.getText().trim();
        }
        Date date=Jdata.getDate();
        SimpleDateFormat ft=new SimpleDateFormat("dd-MM-yyyy");
        Date dataCad=new Date();
        data=ft.format(date);
        //data=ft.format(Datacad);
        //data=Jdata.toString();// getDate().toString();
        privilegio=jprivilegio.getSelectedItem().toString().trim();
        palavrapw=txtpw.getText();
        //confirmarpw=txtconfpw.getText();
         
          username=txtnusuario.getText();
         if(palavrapw == null || nome == null || data == null || genero == null || "Nenhuma".equals(nacionalidade) || "Nenhum".equals(privilegio) ){
            JOptionPane.showMessageDialog(rootPane,"Todos os campos devem ser preenchidos ou selecionados");
          } else {
               ModeloCadastrarFuncionario mc=new ModeloCadastrarFuncionario(nome,nacionalidade,genero,username,palavrapw,privilegio,data);
              
              conexao=new BufferedWriter(new FileWriter("CadastroFuncionario.txt", true));
              ccf.salvardados(conexao,mc);
              JOptionPane.showMessageDialog(rootPane,"Dados salvos com sucesso");
              conexao.close();
              actualizartabela();
          }
        }catch(Exception e){
            JOptionPane.showMessageDialog(this,"Ocorreu um ERRO");
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void balterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_balterarActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
       String nome,nacionalidade,sexo,data,privilegio,palavrapw,username;
       nome=txtnome.getText();//.toString().trim();
       nacionalidade=jCnacionalidade.getSelectedItem().toString().trim();
        if(jRfeminino.isSelected()){
        genero=jRfeminino.getText().trim();
        }else if(jRmasculino.isSelected()){
        genero=jRmasculino.getText().trim();
        }
        Date date=Jdata.getDate();
        SimpleDateFormat ft=new SimpleDateFormat("dd-MM-yyyy");
        Date dataCad=new Date();
        data=ft.format(date);
        privilegio=jprivilegio.getSelectedItem().toString().trim();
        palavrapw=txtpw.getText();
       
        username=txtnusuario.getText();
        ModeloCadastrarFuncionario mc=new ModeloCadastrarFuncionario(nome,nacionalidade,genero,username,palavrapw,privilegio,data);
        int linhaID=Tabelaf.getSelectedRow();
        if(linhaID==-1){
        JOptionPane.showMessageDialog(this, "Nenhuma Linha Selecionada");
        }
        else{
            int c=0;
        int idAtual=0;
        // Defina o ID que você deseja atualizar
        //   int idParaAtualizar = 1;
        // Defina o novo nome
        // Lista para armazenar os registros atualizados
        ArrayList<String> linhasAtualizadas = new ArrayList<>();

        // Caminho do arquivo
        //String caminhoArquivo = "Cadastro.txt";

        try (BufferedReader reader = new BufferedReader(new FileReader("CadastroFuncionario.txt"))) {
            String linha;
            
            while ((linha = reader.readLine()) != null) {
                // Divide a linha em partes usando a vírgula como delimitador
                String[] partes = linha.split(";");
                // Obtém o ID da linha atual
                //int idAtual = Integer.parseInt(partes[0].substring(4));

                // Verifica se é o registro que precisa ser atualizado
                if (idAtual == linhaID) {
                    // Atualiza o nome
                   partes[0] = nome;
                   partes[1]=nacionalidade;
                   partes[2]=genero;
                    // Concatena as partes atualizadas e adiciona à lista
                    linhasAtualizadas.add(String.join("; ", partes));
                } else {
                    // Adiciona a linha sem alterações à lista
                    linhasAtualizadas.add(linha);
                }
                idAtual++;
                c++;
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this,"Erro ao grvar nos arrays");
        }

        // Escreve as linhas atualizadas de volta no arquivo
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("CadastroFuncionario.txt"))) {
            for (String linhaAtualizada : linhasAtualizadas) {
                writer.write(linhaAtualizada + "\n");
            }
        } catch (Exception e) {
           // e.printStackTrace();
           JOptionPane.showMessageDialog(this,"Erro ao escrever no arquivo");
        }

        System.out.println("Atualização concluída com sucesso."+c+"     "+idAtual);
        JOptionPane.showMessageDialog(this,"Atualização concluída com sucesso."+c+"     "+idAtual);
    
        
        }
        

    }//GEN-LAST:event_balterarActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
        // TODO add your handling code here:
                // TODO add your handling code here:
        try{
           
            int linhaselecionada= Tabelaf.getSelectedRow();                                                                                                                                                                           
            if(linhaselecionada==-1){
            JOptionPane.showMessageDialog(this,"Nenhuma Linha Selecionada");
            }else{
                DefaultTableModel modelo=(DefaultTableModel) Tabelaf.getModel();
                        modelo.removeRow(linhaselecionada);
                        }
           ArrayList<String>linharestante=new ArrayList<>();
            try(BufferedReader br=new BufferedReader(new FileReader("CadastroFuncionario.txt"))) {
                
                String linha;
                int idAtual=0;
            while((linha=br.readLine())!=null){
            String[] partes=linha.split(";");
            //int idAtual=Integer.parseInt(partes[0].substring(3));
            
            if(idAtual != linhaselecionada){
            linharestante.add(linha);
            
            }
            idAtual++;
            }              
                
            } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"ERRO ao gravar no ARRAYLIST");
            }
            
            try (BufferedWriter bw=new BufferedWriter(new FileWriter("CadastroFuncionario.txt"))){
                
                for(String linhasrestantes :  linharestante){
                bw.write(linhasrestantes+"\n");
                }
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"ERRO ao gravar no texto");
            }
            
        } catch (Exception e){
             JOptionPane.showMessageDialog(this,"ERRO No TRY principal");
            }   
    }//GEN-LAST:event_beliminarActionPerformed

    private void batualizartabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batualizartabelaActionPerformed
        // TODO add your handling code here:
           actualizartabela();
    }//GEN-LAST:event_batualizartabelaActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String item=txtpesquisar.getText();
          try(BufferedReader leitor=new BufferedReader(new FileReader("CadastroFuncionario.txt"))) {
          
          String linha;
          DefaultTableModel dfm=(DefaultTableModel) Tabelaf.getModel();
          dfm.setRowCount(0);
          while((linha=leitor.readLine())!=null){
          if(linha.contains(item)){
           String[] partir=linha.split(";");
          
          dfm.addRow(partir);
         
          }
          }
          }catch(Exception e){
          
          }
        
        
        
        
        
        
        
    /*  String dados=txtpesquisar.getText().trim();
      if(!(dados.equalsIgnoreCase(" "))){
      ccf.pesquisar(dados);
      Tabelaf.setModel(new DefaultTableModel(ccf.transformarlistaobjeto(), cabecalho));
      
      }else{
      JOptionPane.showMessageDialog(this, "Digite o que queres pesquisar");
      }
        */
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Jdata;
    private javax.swing.JTable Tabelaf;
    private javax.swing.JButton balterar;
    private javax.swing.JButton batualizartabela;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton btsalvar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jCnacionalidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLfoto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRfeminino;
    private javax.swing.JRadioButton jRmasculino;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jprivilegio;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnusuario;
    private javax.swing.JTextField txtpesquisar;
    private javax.swing.JPasswordField txtpw;
    // End of variables declaration//GEN-END:variables
}
