/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ControlCadastroProduto;
import Control.ControleStoke;
import Modelo.ModeloCadastrarProduto;
import Modelo.ModeloStoke;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IMMilengo
 */
public class Stoke extends javax.swing.JFrame {
ControleStoke ccp=new ControleStoke();
    /**
     * Creates new form Stoke
     */
    public Stoke() {
        initComponents();
          ArrayList<String> lista=new ArrayList();
        try {
            BufferedReader ler=new BufferedReader(new FileReader("Stoke.txt"));
            String linha;
            while((linha=ler.readLine())!=null){
            lista.add(linha);
            }
            Collections.sort(lista);
            for(String linhas:lista){
                System.out.println(linhas);
            }
            BufferedWriter escreve=new BufferedWriter(new FileWriter("Stoke.txt"));
            for(String linhas:lista){
            escreve.write(linhas+"\n");
           
            }
            escreve.close();
            
            ler.close();
        } catch (Exception e) {
        }
        
        actualizartabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     String cabecalho[]={"Nome Do Produto","Quantidade de Unidades","Preco Do Produto","ID do Produto","Data ","Prazo de Validade"};
    public void actualizartabela(){
    ccp.preencherarraylist();
    Table.setModel(new DefaultTableModel(ccp.transformarlistaobjeto(),cabecalho));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnomepro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtprecopro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        batualizartabela = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtidproduto = new javax.swing.JTextField();
        quantidadeuni = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        bsalvar = new javax.swing.JButton();
        jData = new com.toedter.calendar.JDateChooser();
        batualizar = new javax.swing.JButton();
        beliminar = new javax.swing.JButton();
        txtpesquisar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        bpesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        jaddprateleira = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        addprateleira = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jValidade = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Stoke");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Nome Do Produto");

        jLabel3.setText("Preco Do Produto");

        txtprecopro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprecoproActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade De Unidades");

        batualizartabela.setText("Actualizar Tabela");
        batualizartabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batualizartabelaActionPerformed(evt);
            }
        });

        jLabel5.setText("ID do Produto");

        txtidproduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidprodutoActionPerformed(evt);
            }
        });

        jLabel6.setText("Data");

        bsalvar.setText("Salvar");
        bsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bsalvarActionPerformed(evt);
            }
        });

        batualizar.setText("Actualizar");
        batualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batualizarActionPerformed(evt);
            }
        });

        beliminar.setText("Eliminar");
        beliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                beliminarActionPerformed(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Stoke");

        bpesquisar.setText("Pesquisar");
        bpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bpesquisarActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Table);

        jaddprateleira.setText("Adicionar à Prateleira");
        jaddprateleira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaddprateleiraActionPerformed(evt);
            }
        });

        jLabel7.setText("Adicionar a Prateleira");
        jLabel7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel8.setText("Prazo de Validade");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(334, 334, 334)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(bpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(34, 34, 34)
                                        .addComponent(txtnomepro, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtidproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtprecopro, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 750, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4))
                                            .addGap(29, 29, 29)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jData, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                    .addComponent(quantidadeuni, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addGap(63, 63, 63)
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jValidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(12, 12, 12)
                                            .addComponent(addprateleira, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                            .addComponent(bsalvar)
                                            .addGap(45, 45, 45)
                                            .addComponent(batualizar)
                                            .addGap(44, 44, 44)
                                            .addComponent(beliminar)
                                            .addGap(18, 18, 18)
                                            .addComponent(batualizartabela, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(37, 37, 37)
                                            .addComponent(jaddprateleira))))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomepro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprecopro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtidproduto, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(quantidadeuni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(addprateleira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsalvar)
                    .addComponent(batualizar)
                    .addComponent(beliminar)
                    .addComponent(batualizartabela)
                    .addComponent(jaddprateleira))
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtprecoproActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprecoproActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprecoproActionPerformed

    private void batualizartabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batualizartabelaActionPerformed
        // TODO add your handling code here:
        actualizartabela();
    }//GEN-LAST:event_batualizartabelaActionPerformed

    private void txtidprodutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidprodutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidprodutoActionPerformed

    private void bsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bsalvarActionPerformed
        // TODO add your handling code here:

        try {
            //File file=new File("Cadastro Produto");
            //file.createNewFile();
            BufferedWriter conexao;
            String nome,preco,quantidade,id,data,validade;
            nome=txtnomepro.getText();
            preco=txtprecopro.getText();
            quantidade=quantidadeuni.getValue().toString();
            id=txtidproduto.getText();

            Date date=jData.getDate();
            SimpleDateFormat ft=new SimpleDateFormat("dd-MM-yyyy");
          //  Date dataCad=new Date();
            data=ft.format(date);
            
            /////////////////////////////////
            /////////Prazo de validade//////
            
            Date prazo=jValidade.getDate();
            SimpleDateFormat pvalidade=new SimpleDateFormat("dd-MM-yyyy");
           // Date dataCad=new Date();
            validade=pvalidade.format(prazo);
            // LocalDateTime data=jData.getDate();
            conexao=new BufferedWriter(new FileWriter("Stoke.txt", true));
           ModeloStoke mcp=new ModeloStoke(nome,preco,quantidade,id,data,validade);
            System.out.println(nome+"   "+preco+"    "+quantidade );
            ccp.salvardados(conexao, mcp);
            conexao.close();
            JOptionPane.showMessageDialog(this, "Dados Salvos com Sucesso");

            //ccp.pro(nome);
            actualizartabela();

            // JOptionPane.showMessageDialog(rootPane,data);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,"ERRO DETECTADO-1");
        }

    }//GEN-LAST:event_bsalvarActionPerformed

    private void batualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batualizarActionPerformed
        // TODO add your handling code here:
        String nome,preco,quantidade,id,data,validade;
        nome=txtnomepro.getText();
        preco=txtprecopro.getText();
        quantidade=quantidadeuni.getValue().toString();
        id=txtidproduto.getText();

        Date date=jData.getDate();
        SimpleDateFormat ft=new SimpleDateFormat("dd-MM-yyyy");
        Date dataCad=new Date();
        data=ft.format(date);
        // LocalDateTime data=jData.getDate();
        
        
            Date prazo=jValidade.getDate();
            SimpleDateFormat pvalidade=new SimpleDateFormat("dd-MM-yyyy");
           // Date dataCad=new Date();
            validade=pvalidade.format(prazo);
        

        ModeloStoke mcp=new ModeloStoke(nome,preco,quantidade,id,data,validade);
        int linhaID=Table.getSelectedRow();
        if(linhaID==-1){
            JOptionPane.showMessageDialog(this, "Nenhuma Linha Selecionada");
        }
        else{
            int c=0;
            int idAtual=0;
            // Defina o ID que você deseja atualizar
            //   int idParaAtualizar = 1;
            // Defina o novo nome

            // Lista para armazenar os registros atualizados
            ArrayList<String> linhasAtualizadas = new ArrayList<>();

            // Caminho do arquivo
            //String caminhoArquivo = "Cadastro.txt";

            try (BufferedReader reader = new BufferedReader(new FileReader("Stoke.txt"))) {
                String linha;

                while ((linha = reader.readLine()) != null) {
                    // Divide a linha em partes usando a vírgula como delimitador
                    String[] partes = linha.split(";");
                    // Obtém o ID da linha atual
                    //int idAtual = Integer.parseInt(partes[0].substring(4));

                    // Verifica se é o registro que precisa ser atualizado
                    if (idAtual == linhaID) {
                        // Atualiza o nome
                        partes[0] = nome;
                        partes[1]=preco;
                        partes[2]=quantidade;
                        partes[3]=id;
                        partes[4]=data;
                        // Concatena as partes atualizadas e adiciona à lista
                        linhasAtualizadas.add(String.join("; ", partes));
                    } else {
                        // Adiciona a linha sem alterações à lista
                        linhasAtualizadas.add(linha);
                    }
                    idAtual++;
                    c++;
                }
            } catch (Exception e) {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this,"Erro ao grvar nos arrays");
            }

            // Escreve as linhas atualizadas de volta no arquivo
            try (BufferedWriter writer = new BufferedWriter(new FileWriter("Stoke.txt"))) {
                for (String linhaAtualizada : linhasAtualizadas) {
                    writer.write(linhaAtualizada + "\n");
                }
            } catch (Exception e) {
                // e.printStackTrace();
                JOptionPane.showMessageDialog(this,"Erro ao escrever no arquivo");
            }

            System.out.println("Atualização concluída com sucesso."+c+"     "+idAtual);
            JOptionPane.showMessageDialog(this,"Atualização concluída com sucesso."+c+"     "+idAtual);

        }
    }//GEN-LAST:event_batualizarActionPerformed

    private void beliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_beliminarActionPerformed
        // TODO add your handling code here:
        try{

            int linhaselecionada= Table.getSelectedRow();
            if(linhaselecionada==-1){
                JOptionPane.showMessageDialog(this,"Nenhuma Linha Selecionada");
            }else{
                DefaultTableModel modelo=(DefaultTableModel) Table.getModel();
                modelo.removeRow(linhaselecionada);
            }
            ArrayList<String>linharestante=new ArrayList<>();
            try(BufferedReader br=new BufferedReader(new FileReader("Stoke.txt"))) {

                String linha;
                int idAtual=0;
                while((linha=br.readLine())!=null){
                    String[] partes=linha.split(";");
                    //int idAtual=Integer.parseInt(partes[0].substring(3));

                    if(idAtual != linhaselecionada){
                        linharestante.add(linha);

                    }
                    idAtual++;
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"ERRO ao gravar no ARRAYLIST");
            }

            try (BufferedWriter bw=new BufferedWriter(new FileWriter("Stoke.txt"))){

                for(String linhasrestantes :  linharestante){
                    bw.write(linhasrestantes+"\n");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,"ERRO ao gravar no texto");
            }

        } catch (Exception e){
            JOptionPane.showMessageDialog(this,"ERRO No TRY principal");
        }

    }//GEN-LAST:event_beliminarActionPerformed

    private void bpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bpesquisarActionPerformed
        // TODO add your handling code here:

        //String dados=txtpesquisar.getText().trim();
        String item=txtpesquisar.getText();
        try(BufferedReader leitor=new BufferedReader(new FileReader("Stoke.txt"))) {

            String linha;
            DefaultTableModel dfm=(DefaultTableModel) Table.getModel();
            dfm.setRowCount(0);
            while((linha=leitor.readLine())!=null){
                if(linha.contains(item)){
                    String[] partir=linha.split(";");

                    dfm.addRow(partir);

                }
            }
        }catch(Exception e){

        }

        /*if(!(dados.equals(" "))){
            ccp.pesquisar(dados);
            tabelaproduto.setModel(new DefaultTableModel(ccp.transformarlistaobjeto(), cabecalho));

        }else{
            JOptionPane.showMessageDialog(this, "Digite o que queres pesquisar");
        }*/
    }//GEN-LAST:event_bpesquisarActionPerformed

    private void jaddprateleiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaddprateleiraActionPerformed
        // TODO add your handling code here:
        int produtoselecionado=Table.getSelectedRow();
        int quantiAdd=Integer.parseInt(addprateleira.getValue().toString());
        int contador=0;
        String linha;
        String alterar = null;
       ArrayList<String> lista=new ArrayList<>();
        try(BufferedReader ler= new BufferedReader(new FileReader("Stoke.txt"))) {
           while((linha=ler.readLine())!=null){
           if(contador==produtoselecionado){
           alterar=linha;
           }else{
               lista.add(linha);
           }
           contador++;
           } 
           BufferedWriter escritor=new BufferedWriter(new FileWriter("Stoke.txt"));
            String partir[]=alterar.split(";");
           int novaquanti=Integer.parseInt(partir[1])-quantiAdd;
           
           escritor.write(partir[0]+";"+String.valueOf(novaquanti)+";"+partir[2]+";"+partir[3]+";"+partir[4]+";\n");
           for(String linhas:lista){
           escritor.write(linhas+"\n");
               System.out.println(linhas+"\n");
           }
           
            
           ler.close();
          escritor.close();
          ModeloCadastrarProduto prateleira=new ModeloCadastrarProduto(quantiAdd,partir[0],alterar);
          ControlCadastroProduto ccpadd=new ControlCadastroProduto();
          ccpadd.AddPrateleira(prateleira);
        } catch (Exception e) {
        JOptionPane.showMessageDialog(rootPane, "ERRO");
        }
        /*try(BufferedWriter escritor=new BufferedWriter(new FileWriter("Stoke.txt"));) {
          
        } catch (Exception e) {
        }*/
        
    }//GEN-LAST:event_jaddprateleiraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stoke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stoke().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JSpinner addprateleira;
    private javax.swing.JButton batualizar;
    private javax.swing.JButton batualizartabela;
    private javax.swing.JButton beliminar;
    private javax.swing.JButton bpesquisar;
    private javax.swing.JButton bsalvar;
    private com.toedter.calendar.JDateChooser jData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.toedter.calendar.JDateChooser jValidade;
    private javax.swing.JButton jaddprateleira;
    private javax.swing.JSpinner quantidadeuni;
    private javax.swing.JTextField txtidproduto;
    private javax.swing.JTextField txtnomepro;
    private javax.swing.JTextField txtpesquisar;
    private javax.swing.JTextField txtprecopro;
    // End of variables declaration//GEN-END:variables
}
