/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Control.ControlTelaDeLogin;
import Modelo.ModeloTelaDeLogin;
import Modelo.ModeloTelaPrincipal;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author IMMilengo
 */
public class TelaDeLogin extends javax.swing.JFrame {
ControlTelaDeLogin ctl=new ControlTelaDeLogin();
int contador =0;    
/**
     * Creates new form TelaDeLogin
     */
    public TelaDeLogin() {
        initComponents();
          setLocationRelativeTo(this);
          
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtidentificacao = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        bentrar = new javax.swing.JButton();
        pwsenha = new javax.swing.JPasswordField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tela De Login");

        jPanel2.setBackground(new java.awt.Color(153, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel1.setText("Nome de Usuário");

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel2.setText("   Insira Suas Credenciais");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 18)); // NOI18N
        jLabel3.setText("Senha");

        txtidentificacao.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)), "Usuário"));

        bentrar.setText("Entrar");
        bentrar.setBorder(new javax.swing.border.MatteBorder(null));
        bentrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bentrarActionPerformed(evt);
            }
        });

        pwsenha.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "Senha"));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(txtidentificacao, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                            .addComponent(jLabel3)
                            .addComponent(pwsenha)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(bentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtidentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pwsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bentrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bentrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bentrarActionPerformed
            String Usuario = null,Senha = null;
            //identificacao=txtidentificacao.getText();
            //senha=pwsenha.getText();
            
           LocalDate dia=LocalDate.now();
           String data=dia.toString();
           
           
        if (txtidentificacao.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite o nome de usuario");
            txtidentificacao.requestFocus();
            return;
        }
        if (pwsenha.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Digite a senha");
            pwsenha.requestFocus();
            return;
        }

        String usuarioFuncionario = txtidentificacao.getText().toString().trim();
        String senhaFuncionario = pwsenha.getText().toString().trim();
        String Nome = null;
        String Nivel = null;

        try {
            //INICIO DO SEGUNDO WHILE
            BufferedReader ler = new BufferedReader(new FileReader("CadastroFuncionario.txt"));
            String linha;
            contador++;
            while ((linha = ler.readLine()) != null) {
                String campos[] = linha.split(";");
                Nome = campos[0];
                Usuario = campos[3];
                Nivel = campos[5];
                Senha = campos[4];

                if (usuarioFuncionario.equalsIgnoreCase(Usuario) && senhaFuncionario.equalsIgnoreCase(Senha)) {
                    contador = 0;
                    break;
                } else {

                }
            }//SAÍDA DO WHILE 1
            if (contador == 0) {
                
                
              if(Nivel.equals("Administrador")){
                ctl.acesso1();
                this.hide();
                JOptionPane.showMessageDialog(rootPane, "Seja BemVindo "+Nivel+"\n "+Nome);
               BufferedWriter escrito=new BufferedWriter(new FileWriter("QuemLogou"));
                escrito.write(Nivel);
                escrito.close();
                }else if(Nivel.equals("Funcionário")){
               
                 ctl.acesso2();
                 this.hide();
                JOptionPane.showMessageDialog(rootPane, "Seja BemVindo "+Nivel+"\n "+Nome);
               
                BufferedWriter escrito=new BufferedWriter(new FileWriter("QuemLogou"));
               escrito.write(Nivel);
               escrito.close();
                }
                 BufferedWriter loginhist=new BufferedWriter(new FileWriter("login.txt",true));
                loginhist.write(Usuario+";");
                loginhist.write(Senha+";");
                loginhist.write(data+";\n");
                 
                 loginhist.close();
               
           

                //JOptionPane.showMessageDialog(null, "Bem Vindo: " + Nome);
                 //TelaPrincipall tp=new TelaPrincipall();
                 //   tp.setVisible(true);
                dispose();
            }
            if (contador == 1) {
                JOptionPane.showMessageDialog(null, "Acesso negado - 1");
            }
            if (contador == 2) {
                JOptionPane.showMessageDialog(null, "Acesso negado - 2");
            }
            if (contador == 3) {
                JOptionPane.showMessageDialog(null, "Acesso negado" + " \nNúmero de tentativa excedidio");
               //txtInf.setText("Acesso negado Número de tentativa excedidio");
                this.hide();
                
            }
        } catch (Exception e) {
        }
           
           
           
           
           
           
           /*         
        try { BufferedReader ler=new BufferedReader(new FileReader("CadastroFuncionario.txt"));
            String Linha;
          
            while((Linha=ler.readLine())!=null){
           
            String partes[]=Linha.split(";");
            if( !(identificacao == null ? partes[3] != null : !identificacao.equals(partes[3])) && !(senha == null ? partes[4] != null : !senha.equals(partes[4]))){
             // encontrado=true;
             //break;
               
              if(partes[5].equals("Administrador")){
                ctl.acesso1();
                this.hide();
                JOptionPane.showMessageDialog(rootPane, "Seja BemVindo "+partes[5]+"\n "+partes[0]);
               BufferedWriter escrito=new BufferedWriter(new FileWriter("QuemLogou"));
                escrito.write(partes[5]);
                escrito.close();
                }else if(partes[5].equals("Funcionário")){
               
                 ctl.acesso2();
                 this.hide();
                JOptionPane.showMessageDialog(rootPane, "Seja BemVindo "+partes[5]+"\n "+partes[0]);
               
                BufferedWriter escrito=new BufferedWriter(new FileWriter("QuemLogou"));
               escrito.write(partes[5]);
               escrito.close();
                }
                 BufferedWriter loginhist=new BufferedWriter(new FileWriter("login.txt",true));
                loginhist.write(partes[3]+";");
                loginhist.write(partes[4]+";");
                loginhist.write(data+";\n");
                 
                 loginhist.close();
               
                 
            }else{
            }
            
            }
            
            
            } catch (Exception e ) {
         JOptionPane.showMessageDialog(rootPane, "ERRO");
            }*/
// TODO add your handling code here:
       
    }//GEN-LAST:event_bentrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDeLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDeLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bentrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPasswordField pwsenha;
    private javax.swing.JTextField txtidentificacao;
    // End of variables declaration//GEN-END:variables
}
